[workspace]
authors = ["Tim <timcash@gmail.com>"]
channels = ["conda-forge"]
name = "cadquery"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.14"
cadquery = "*"
